VDR-Rectools Optionen : echo "Starte VDR-Rectools..."
- Aufnahme reparieren : /usr/bin/vdr-rectools repair_single
- Werbung schneiden   : /usr/bin/vdr-rectools cut_single
- Platz sparen (H.265): /usr/bin/vdr-rectools shrink_single
- Plex/Kodi Sync      : /usr/bin/vdr-rectools sync_single
