location ~ ^/(config|explorer|log_viewer|rectools_confirm|job_status|job_queue|job_dispatcher|pes2ts_explorer|job_wait)\.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php-fpm.sock;
}